<div class="main">
<?php
	include 'linkleftcont.php';
?>
<div class="bannerimg">
<div class="bannerimg1"><img src="images/art1.png" /></div>
<div class="bannerimg2"><img src="images/art2.png" /></div>
<div class="bannerimg2" style="margin-top:2px;"><img src="images/art3.png" /></div>
</div>

<div class="linkcont" style="margin-top:0px; height:auto;">
<div class="linkconttop">Arts and Crafts</div>
<div style="float:left; padding:8px; height:auto; width:auto;">

<b style="color:#eb731a">Zorig Chusum: the thirteen traditional crafts of Bhutan</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  Though the thirteen traditional arts and crafts were practiced right from the immemorial times, it is commonly understood that it was formally categorized during the reign of Gyalse Tenzin Rabgay, the fourth temporal ruler of Bhutan. The thirteen arts and crafts are categorized as follows:<br /><br />
  
<b style="color:#eb731a">Shing zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
When considering the history of human dwellings, the use of timber predates the use of stones. Evidence of buildings framed with timber can be found in many countries, including even the pyramids of Egypt. Most virgin primeval forests that existed were used for structural framework and this began to develop into an art. Large temples were built simply using timber and without any metal fasteners. Instead, they were joined together using notches with thick pegs and nails made of wood, and these wooden structures were designed to last for centuries. Slowly, in many countries, woodwork became a profession and the craftsmen became the engineers, architects, carpenters and builders of their age. However, by the mid-nineteenth century, this craft began to disappear from many parts of the world as mechanization of works began when many industries appeared.<br /><br />

While most people across the world are trying to rediscover and learn the secrets of this old tradition, the Bhutanese still practice this ancient art termed shingzo. The master craftsman known locally as Zow chen and Zows are instrumental in fashioning intricate designs that goes into the construction of our fortresses-the Dzongs, our palaces, our temples and monasteries and the traditional Bhutanese farm houses. The Dzongs that have its origin in the 17th century features some of the most elaborate wood works and designs that draw appreciation not only from the Bhutanese populace but from outside visitors as well.<br /><br />
People interested in becoming carpenters serve as apprentice under a master carpenter for a few years till they develop the confidence to practice the skills on their own. Master carpenters are found all over the kingdom and for every important structure to be raised they are called upon to contribute. A master carpenter who is still revered today is the Zow Balep, whose architectural skills can still be witnessed today in the ancient fortress of Punakha Dzong.<br /><br />

<b style="color:#eb731a">Do zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  Do zo as it is widely known is an old craft that is still being practiced today by the Bhutanese. Just as the many temples and palaces that have been built in stone the world over, the Bhutanese temples, Dzongs, the Chortens or the stupas and the farm houses are all built of stones. Indeed no construction ever takes place without the use of stones. Classic examples of stone work are those of Chorten Kora in Tashiyangtse in eastern Bhutan and Chendebji chorten in central Bhutan.<br /><br />
  
<b style="color:#eb731a">Par zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  Par zo or carving is another traditional art that has been perfected by the Bhutanese. The major carvings are carried out on stone, wood and slate. The traditional designs crafted on these materials create some distinctive art works.<br /><br />
Since Bhutan has been blessed with an abundant variety of wood, woodcarving is seen in a variety of forms. The wooden masks that feature during the annual religious festivals are all carved out of wood besides the many traditional motifs that are engraved on the Bhutanese houses and on Dzongs. Besides, a unique wood carving that draws attraction are the phalluses of various sizes and shapes that are hung on the four corners of the Bhutanese houses and stuck onto the main entrance of the door ways. These carved wooden phalluses are also displayed by the Acharyas- the clowns during the religious festivals as a sign to bless the spectators and drive away the evils and misfortunes.<br /><br />

Another important art that is being practiced is the art of slate carving. The master craftsman is known as Do Nag Lopen and the material used is the slate found in abundance in both western and Eastern Bhutan. While slate carving is not as diverse as stone and wood work, yet one can come across many religious scriptures, mantras and images of deities being carved onto slates besides the religious figures. Slate works are fund mostly in religious places such as Dzongs, temples and chortens.<br /><br />
Another important craft that has survived in Bhutan is the stone carving. While it is certainly less evident, yet the water driven grinding mills are classic examples of stone works. The huge grinding mills are still used by people in the far flung villages of Bhutan. One can also come across hollowed – out stones used for pounding grains and troughs for feeding cattle and horses.<br /><br />

<b style="color:#eb731a">Lha zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  Bhutanese paintings represent the quintessential of the Bhutanese art and craft tradition. An old art that has been practiced since antiquity, painting captures the imagery of the Bhutanese landscape. The work of master painters known as Lha Rip are reflected in every architectural piece be it the massive Dzongs, the temples and the monasteries, the nunneries and the stupas or a modest Bhutanese home. Indeed, paintings and the varied colors and hues epitomize the Bhutanese art and craft.<br /><br />
The art of painting is revered and painters are believed to accumulate merit. Young novices are taught by the master Lha Rips and the huge scrolls of thangkha or thongdrols that depicts religious figures and displayed during religious festivals are some classic works. A mere sight of these huge scrolls is believed to deliver us to nirvana. Thus, it brings merit not only to the believers but for the painters as well.<br>
  The materials used in Bhutan are the natural pigmented soils that are found in most places in the country. These natural soil pogments are of different colours and are named accordingly. The black lumps of soil is known as 'sa na', and red lumps as 'Tsag sa', for instance.<br /><br />
  
<b style="color:#eb731a">Jim zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  Jim zo or clay work is an ancient craft having been practiced and passed on over the centuries. This art work preceded other sculpture works such as bronze or other metal works. Statues of deities, gods and goddesses and other prominent religious figures in fact exemplify clay work in Bhutan. Every monastery, temple and the Dzongs have in them installed clay statues from where pilgrims and devout Buddhists draw their inspiration from. The master craftsmen are known as Jim zo lopen and the skill is imparted to the young novices through vigorous trainings spread over the years.<br /><br />
Besides the clay statues, the tradition of clay potteries is still alive though much of the potteries are now being used as show pieces and flower vases. While the art of modeling statues are confined to men, the art of pottery is normally the handiwork of women. While we find three distinctive types of clayware: earthenware, stoneware and the china-clayware, in Bhutan, we find only the first type, the earthenware.<br>
  What is required for success in the work on clay is the composition of clay by using balanced materials, skills in shaping the wet clay and firing to the correct temperature. The baked items were then coated with lac to render them waterproof. While this tradition is almost dying the women of Lhuentse and Paro still try and keep this tradition alive.<br /><br />
  
<b style="color:#eb731a">Lug zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  The period in history between the Stone Age and Iron Age is known as the Bronze Age because bronze was commonly used to cast containers such as cups, urns, and vases. People also shaped bronze into battle-axes, helmets, knives, shields, and swords. They also made it into ornaments, and sometime even into primitive stoves. Bronze was developed about 3500 BC by the ancient Sumerians in the Tigris-Euphrates valley. Historians are unsure of how this alloy was discovered, but they believe that bronze may have first been made accidentally when rocks, rich in copper and tin, were used to build campfire rings. As fire heated these stone, the metals may have melted and mixed, forming bronze. This theory is supported by the fact that bronze was not developed in North America, where natural tin and copper ores are rarely found in the same rocks. Bronze appeared in both Egypt and China around 2000 BC. The earliest bronze castings were made in sand, and this method is still used today, even for casting bells. However, clay and stone moulds were developed later on. Clay is usually used nowadays for making bells.<br /><br />
Bronze casting in Bhutan was introduced only in the 17th century and was mainly spread through the visiting Newari artisans that came from Nepal. The Newars of Nepal were first invited by Zhabdrung Nawang Namgyal to cast bronze statues and religious items such as bells and water offering bowls. It was through these artisans that the art was introduced and today, a lot of Bhutanese people are into bronze casting.<br /><br />

<b style="color:#eb731a">Shag zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  The art of wood turning is known as Shag Zo and is traditionally practiced by the people of Trashiyangtse in eastern Bhutan. As a vibrant art, the master craftsmen are known as Shag Zopa. They are famed for wooden cups and bowls traditionally known as dapas and phobs. These wooden bowls made of special wooden knots known as Zaa are highly priced and till the advent of steel and brass plates were once used as plates by the Bhutanese people at large.  Today they are being sold to the outside visitors and offered as gifts.<br /><br />
Another village that practices wood turning is the small village in eastern Bhutan known as Khengkhar. The villagers here are known for producing traditional wooden wine containers known as jandup.<br /><br />

<b style="color:#eb731a">Gar zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  The art blacksmithing began with the Iron Age when primitive man first began making tools from iron. Thus, the art of crafting the crude metal found in certain type of rocks and soil into a usable implement has been around for a long time. Some of the tools that man used were spear or arrow-tips, crude axes and knives as well as agricultural implements.<br /><br />
Iron smelters were small furnaces built from rock that could withstand repeated heating. These furnaces looked like bee-hives with an opening at the top and an entrance on the side. The furnace was filled with iron-ore and charcoal and then set to fire. When the temperature rises above 2,800 Fahrenheit, the iron flows and forms balls, which are later hammered and made into various implements.<br /><br />
Black smithy in Bhutan began sometime in the late 14th century and it is believed that it was introduced by a Tibetan saint known as Dupthob Thangtong Gyalpo. He has been revered as the master engineer for his skill in casting iron chains and erecting them as bridges over gorges. In Bhutan, he is supposed to have built about eight suspension bridges and one can still come across a bridge over Paro Chu linking the highway to the famous Tachog lhakhang in Paro. One can also come across the remains of these once highly used iron chains in Trashigang and at the National Museum in Paro.<br /><br />
While black smithy is almost a dying art, yet one can still come across the Tibetan settlers especially in Trashigang practicing this art.<br /><br />

<b style="color:#eb731a">Troe ko</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  Ornaments are widely used by the Bhutanese women and the tradition of making ornaments is still vibrant in Bhutan. Master craftsmen who skill in shaping beautiful ornaments are regarded as Tro Ko Lopen. Using precious stones such as corals and turquoise, silver and gold, these master craftsmen shape out ornaments such as necklaces, bangles, earrings, rings worn on fingers, brooches, amulets to contain ritual objects, traditional containers to carry the much chewed beetle nuts, ritual objects and many more.<br /><br />
  
<b style="color:#eb731a">Tsha zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  Most of the forests in Bhutan are richly stocked with bamboos and canes of various species. O,Taking advantage of the abundant natural resources, people have mastered their skills in weaving cane and bamboo products. Widely known as Tshar Zo, this art is spread throughout the country products such as baskets, winnowers, mats, containers known as Palangs and bangchungs are all made of bamboo. However, the people of Kangpara in eastern Bhutan and the Bjokaps of Central Bhutan are pioneer master craftsmen. Their products are now sold out to tourists earning them an additional income.<br /><br />
  
<b style="color:#eb731a">De zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  Paper-making is another art that has found roots in Bhutan. People engaged in producing the traditional Bhutanese paper or De zo are known as Dezop.  Traditional papers were widely used in the past and most of the religious scriptures and texts were written on Dezho's using traditional Bhutanese ink and at times in gold. While the presence of readily available modern paper has overtaken the market, yet people still produce Deshos which is used as carrying bags, wrappers for gifts and even used as envelopes. The art still continues in Trashiyangtse where the raw material is readily available.<br /><br />
  
<b style="color:#eb731a">Tshem zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  Tzhem zo or the art of tailoring is a popular art amongst the Bhutanese. This art can be broadly classified as Tshem drup or the art of embroidery, lhem drup or the art of appliqué and Tsho lham or the art of traditional Bhutanese boots. The art of embroidery and appliqué are normally practiced by the monks. Using this art they produce large religious scrolls known as Thangkas that depicts Gods and Goddesses, deities and saints.<br /><br />
Traditional boots are normally the work of Bhutanese lay men. These boots worn by officials during special functions and gatherings are made of leather and cloth. While boot making is n old craft, its origin is unknown. Special craftsmen in the villages also make simple boots from uncured leather. However, this is a vanishing practice in the villages though it has picked up recently in the urban centers with support from the government.<br /><br />
The third category is the simple tailors that skill in sewing the Bhutanese traditional dresses known as Gho and Kira.<br /><br />

<b style="color:#eb731a">Thag zo</b><div style="mso-element: para-border-div; border-left: medium none; border-right: medium none; border-top: medium none; border-bottom: 2.25pt double #fdf5a3; padding-bottom: 4.0pt; margin-bottom:6px; margin-top:4px;"></div>
  An integral part of the Bhutanese life is the textile. As such the art of weaving is widely practiced in Bhutan. However, women of eastern Bhutan are skilled in weaving and some of the highly priced textiles are all woven by them. In the past, textiles were paid as tax to the government in place of cash and people from western Bhutan travelled all the way to Samdrup Jongkhar to buy woven textiles. Textiles are woven of cotton, raw cotton and silk and intricate motifs are woven into the cloth.<br /><br />
Khoma village in Lhuentse is famous for Kushithara, while Rahi and Bidung are known for bura textiles namely Mentsi Matha and Aikapur. One type of cotton fabric woven in Pemagatshel is the Dungsam Kamtham. Decheling village in Samdrup Jongkhar is known for their cotton fabric as the Decheling Kamtham derived from the name of their village.<br /><br />
Adang village in Wangdue Phodrang is known for textiles such as Adang Mathra, Adang Rachu and Adang Khamar while the Bumthaps in central Bhutan are kown for Bumthap Mathra and Yathra, both textiles woven out of Yak and sheep hair. People of Nabji and Korphu in Trongsa are known for textiles woven out of nettle fibers. Weaving is also a vocation amongst the Brokpas of Merak and Sakteng. Men contribute in spinning wool into threads. They weave from yak hair and sheep wool.<br /><br />
There are four types of looms that are used by the Bhutanese weavers. They are the blackstrap looms, the horizontal fixed looms, the horizontal framed looms and the card looms. The predominant type is the back strap loom and is used mostly by weavers from eastern Bhutan.  They are set up on the porches or in thatched sheds to protect weavers and the cloth from the sun and rain. Card looms and horizontal frame looms are also used. The back straps are the indigenous looms while the horizontal frame looms and the card looms made their entry into Bhutan from Tibet.
</div>
</div>

</div>