<div class="main">
<?php
	include 'linkleftcont.php';
?>
<div class="bannerimg">
<div class="bannerimg1"><img src="images/peo1.png" /></div>
<div class="bannerimg2"><img src="images/peo2.png" /></div>
<div class="bannerimg2" style="margin-top:2px;"><img src="images/peo3.png" /></div>
</div>

<div class="linkcont" style="margin-top:0px; height:auto;">
<div class="linkconttop">People  Society and Religion</div>
<div style="float:left; padding:8px; height:auto; width:auto;">
Bhutanese people can be  generally categorized into three main ethnic groups. The Tshanglas, Ngalops and  the Lhotshampas. The other minority groups are the Bumthaps and the Khengpas of  Central Bhutan, the Kurtoeps in Lhuentse, the Brokpas and the Bramis of Merak  and Sakteng in eastern Bhutan, the Doyas of Samtse and the Monpas of Rukha  villages in Wangdue Phodrang. Together the multiethnic Bhutanese population  number slightly more than 6,00,000.<br /><br />
Tshanglas: The Tshanglas  or the Sharchops as they are commonly known are considered the aboriginal  inhabitants of eastern Bhutan. Tshanglas or the descendants of Lord Brahma as  claimed by the historians speak Tshanglakha and are commonly inhabitants of  Mongar, Trashigang, Trashi Yangtse, Pema Gasthel and Samdrup Jongkhar. Besides  cultivation of maize, rice, wheat, barley and vegetables, the Tshanglas also  rear domestic animals to supplement their living. Weaving is a popular  occupation of women. They produce beautiful fabrics mainly of silk and raw  silk.<br /><br />
<strong>Ngalops:</strong>&nbsp;The Ngalops who  have settled mostly in the six regions of western Bhutan are of Tibetan origin.  They speak Ngalopkha, the polished version of Dzongkha which is the national  language of Bhutan. Agriculture is their main livelihood. They cultivate rice,  wheat, barley, maize etc, among others. In the regions of Thimphu and Paro  apple is also cultivated as cash crop. They are known for Lozeys, or ornamental  speech and for Zheys, dances that are unique to the Ngalops.<br /><br />
<strong>Lhotshampas:</strong>&nbsp;The Lhotshampas  who have settled in the southern foothills are the latest to settle in the  country. It is generally agreed that they migrated from Nepal in the beginning  of the 19th&nbsp;century mostly coming in as laborers. They speak  Lhotshamkha which is the Nepali language and practice Hinduism. One can find  various castes of Lhotshampas including Bhawans, Chhetris, Rai's, Limbus,  Tamangs, Gurungs, and the lepchas. They essentially depend on agriculture and  cultivate cash crops such as like ginger, cardamom, oranges, etc.<br /><br />
<strong>The Bumthaps, Mangdeps  and Khengpas:</strong> The people who speak Bumtapkha, Mangdepkha and khengkha  respectively inhabit the central pockets of Bhutan. The Bumthaps cultivate buck  wheat, potatoes and vegetables. A section of this population also rear yaks and  sheep and produce fabrics of wool and yak hair. The Mangdeps depend on  cultivation of rice, wheat, maize, vegetables, etc besides rearing domestic  animals. The khengpas also depend on agriculture similar to the Mangdeps.  However, they are also known for the bamboo and cane craft.<br /><br />
<strong>Kurtoeps:</strong>&nbsp;Kurtoeps are the  other category of people in the east. They inhabit the district of Lhuentse and  the villages are found spread along the banks of Kurichu. Khoma women are  expert weavers and are known for their skill in weaving the grandiose  Kushithara.<br /><br />
The Brokpas and the  Bramis:&nbsp;The  Brokpas and the Bramis are a semi nomadic community. They are settled in the  two villages of Merak and Sakteng in eastern Bhutan. They mostly depend on yaks  and sheep for livelihood. Living in the high altitude zones they hardly take up  agriculture. They speak a different dialect and have their own unique dress  that is made of yak hair and sheep wool. They are also experts in cane and  bamboo crafts.<br /><br />
<strong>The Layaps:</strong>&nbsp;To the extreme  north are the Layaps who speak the layapkha. Like the Brokpas, they are also  semi nomads whose source of livelihood is dependent on yaks and sheep the  products of which they barter with the people of Wangdue Phodrang and Punakha  with rice, salt and other consumables.<br />
  <strong>The Doyas:&nbsp;</strong>These are the other tribal community and are settled  mostly in southern Bhutan. They are considered the aboriginal inhabitants of  western and central Bhutan, who over the years settled in the present areas in  Dorokha. They have a dialect of their own and dress in their own unique style.<br /><br />
<strong>Monpas:</strong>&nbsp;The Monpas are a  small community in Rukha under Wangdue Phodrang. Together with the Doyas they  are also considered the original settlers of central Bhutan. They speak a  different dialect unique to their own but one that is slowly ding as these  people are now being absorbed into the main stream Bhutanese society.<br /><br />

  <b style="color:#eb731a">The Bhutanese society:</b><br /><br />

The Bhutanese society is  free of class or caste system and any inhibition that is detrimental for a  society to progress. Slavery was abolished by the Third King Jigme Dorji  Wangchuck in the early 1950s through a royal edict. Though, few organizations  to empower women have been established a few years back, in general the  Bhutanese have always been gender sensitive. In general ours is an open and a  good-spirited society.<br /><br />
Living in a Bhutanese  society generally means understanding some basic norms like Driglam Namzha, the  traditional etiquette. This is a norm that desires members of the society to  conduct themselves in public places. Wearing a scarf when visiting a Dzong or  an office, letting the elders and the monks serve themselves first, offering  felicitation scarves during ceremonies such as marriages and promotions,  greeting elders or senior officials are some simple manners that harmonizes and  binds together the Bhutanese society.<br /><br />
Normally, greetings are  limited to saying Kuzuzangpo amongst equals. For seniors and elders, the  Bhutanese bow their head a bit and say kuzuzangpola. But, the western ways of  shaking hands has become an accepted norm.<br /><br />
The Bhutanese are also  fun-loving people. Dancing, singing, playing archery, stone pitching, partying,  social gatherings etc. are common things that one observes. Visiting friends  and relatives at any hour of the day without any advance notice or appointment  clearly depicts the openness of the Bhutanese society.<br /><br />

  <b style="color:#eb731a">Religion:</b><br /><br />

Bhutan is a Buddhist  country and people refer to it as the last stronghold of Vajrayana Buddhism.  Buddhism was first introduced by the Indian Tantric master Guru Padmasambhava  in the 8th century. Till then people by and large worshipped all forms of  nature, remnants of which are still evident even today in some remote villages  in the country. The older form of religion was referred to as Bon and was accompanied  by offerings of animal sacrifice and worshipped a host of deities invoking and  propitiating them. They believed in invisible forces and considered them as the  rightful owners of different elements of nature. Mountain peaks considered as  abodes of Guardian deities (Yul lha), the lakes as inhabited by lake deities  (Tsho mem), cliffs resided by cliff deities (Tsen), land belonging to the  subterranean deities (Lue), land inhabited by (Sabdag), water sources inhabited  by water deities (Chu gi Lhamu), and dark places haunted by the demons (due)  etc.<br /><br />
With the visit of  Padmasambhava, Buddhism began to take firm roots and especially led to the  propagation of the Nyingmapa (the ancient or the older) school of Buddhism.<br /><br />
The visit of Phajo  Drugom Zhigpo's from Ralung in Tibet to Bhutan in 1222 marks another milestone  in the history of Bhutan and in Buddhism. He was instrumental in introducing  yet another school of Buddhism – the Drukpa Kagyu that is today the state  religion of the country. His sons and descendants were also instrumental in  spreading it to many other parts in western Bhutan.<br />
  <br />
  By far the greatest contributor was Zhabdrung Nawang Namgyal. His arrival in  1616 from Tibet marks another landmark. He was not only able to bring under his  domain the various Buddhist schools that had cropped up in many parts of  western Bhutan but unify the country as a one whole nation-state and give it a  distinct identity.<br /><br />
Buddhism is still  vibrant and alive. The Dzongs, monasteries, stupas, prayer flags, and prayer wheels  punctuate the Bhutanese landscape. The chime of ritual bells, sound of gongs,  people circumambulating temples and stupas, fluttering prayer flags, red robed  monks conducting rituals, among many others are all living case in point to  reveal that Buddhism is an essential ingredient of a Bhutanese life.<br /><br />

  <b style="color:#eb731a">Animism:</b><br /><br />

Though referred to as  the last Vajrayana Buddhist country, yet one may still come across animistic  traditions and beliefs being practiced by the people. Nature worship and animal  sacrifice are still a part of the Bhutanese worship. Every village has a local  priest or a shaman to preside over the rituals. Some of the common nature  worship being practiced are the&nbsp;<em>Cha</em>&nbsp;festival in Kurtoe, the&nbsp;<em>Kharphud</em>&nbsp;in  Mongar and Zhemgang, the&nbsp;<em>Bala Bongko</em>&nbsp;in Wangdue Phodrang, the&nbsp;<em>Lombas</em>&nbsp;of  the Haaps and the Parops, the&nbsp;<em>Jomo Solkha</em>&nbsp;of the Brokpas, the&nbsp;<em>Kharam</em>&nbsp;amongst  the Tshanglas and the&nbsp;<em>Devi Puja</em>&nbsp;amongst our southern  community. All these shamanistic rituals are being performed to keep at bay the  evil spirits, to bring in prosperity, to cure a patient, or to welcome a new  year. In all of these rituals a common feature is the offering of animals  ranging from slaughter of an ox, fish a chicken or a goat.
</div>
</div>
</div>